M48
; DRILL file {KiCad (6.0.0-0)} date Saturday, 09 April 2022 at 12:07:12
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-04-09T12:07:12+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.250
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.700
%
G90
G05
T1
X86.36Y-66.29
X86.36Y-78.99
T2
X95.0Y-42.8
X95.0Y-103.1
T0
M30
